name: my_env
dependencies:
  - python=3.9.13
  - pip:
    - azureml-defaults
    - azureml-core
    - azure-ai-ml
    - azureml-mlflow
    - scikit-learn
    - xgboost
    - numpy
    - pandas
    - mlflow
